### ISSUE TITLE
loginForTest 'Not supported outside of Dev and Testing Environment' with NODE_ENV=dev

### ISSUE THREAD

**Issue by b-zee** [maidsafe/safe_app_nodejs#274]
Version: 0.9.1
OS: Windows 10

Consider the following example:

```javascript
// index.js

const safeApp = require('@maidsafe/safe-node-app');

(async () => {
    const app = await safeApp.initialiseApp({ id: '1', name: '2', vendor: '3' });
    await app.auth.loginForTest();
})();
```

Launching the script in the following way:
```
$ NODE_ENV=dev npm install @maidsafe/safe-node-app
$ NODE_ENV=dev node index.js
```

Gives the following result:
```
(node:15980) UnhandledPromiseRejectionWarning: 1012:
    Not supported outside of Dev and Testing Environment.
    Set NODE_ENV=dev
    at module.exports (C:\src\node_modules\@maidsafe\safe-node-app\src\native\_error.js:32:10)
    at AuthInterface.loginForTest (C:\src\node_modules\@maidsafe\safe-node-app\src\api\auth.js:386:13)
    at C:\src\index.js:5:20
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
(node:15980) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15980) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Passing the option `forceUseMock` to `initialiseApp` does not produce this error but results in issue #275  (`lib.test_create_app is not a function`).

_Confirmed it to be working just fine in 0.8.1_

**Comment by b-zee** [comment]
Solved as the `NODE_ENV` should be `testing` for this to work. See pull request #276.
