### ISSUE TITLE
loginForTest results in 'lib.test_create_app is not a function'

### ISSUE THREAD

**Issue by b-zee** [maidsafe/safe_app_nodejs#275]
Version: 0.9.1

Consider the following example:

```javascript
// index.js

const safeApp = require('@maidsafe/safe-node-app');

(async () => {
    const app = await safeApp.initialiseApp({ id: '1', name: '2', vendor: '3' }, null, { forceUseMock: true });
    await app.auth.loginForTest();
})();
```

Launching the script in the following way:
```
$ NODE_ENV=dev npm install @maidsafe/safe-node-app
$ NODE_ENV=dev node index.js
```

Gives the following result:
```
(node:7352) UnhandledPromiseRejectionWarning: TypeError: lib.test_create_app is not a function
    at AuthInterface.loginForTest (C:\src\node_modules\@maidsafe\safe-node-app\src\api\auth.js:406:16)
    at C:\src\index.js:5:20
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
(node:7352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7352) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bochaco** [comment]
@b-zee , try with running your app with `NODE_ENV=test` instead
