### ISSUE TITLE
Error calling getWebIds(): -1002: '_public' not found in the access container

### ISSUE THREAD

**Issue by theWebalyst** [maidsafe/safe_app_nodejs#374]
When I call `app.web.getWebIds()` immediately after `inistialiseApp()` I get the following error:
```
stack : "-1002: '_public' not found in the access container↵    at module.exports (/home/mrh/safe-releases/2017-09-21_Alpha_2/safe-browser-v0.13.0-linux-x64-dev/resources/app.asar/node_modules/@maidsafe/safe-node-app/src/native/_error.js:32:10)↵    at args.push.ffi.Callback.restArgs (/home/mrh/safe-releases/2017-09-21_Alpha_2/safe-browser-v0.13.0-linux-x64-dev/resources/app.asar/node_modules/@maidsafe/safe-node-app/src/native/_base.js:105:27)↵    at /home/mrh/safe-releases/2017-09-21_Alpha_2/safe-browser-v0.13.0-linux-x64-dev/resources/app.asar/node_modules/ffi/lib/callback.js:66:25"
```

### Prerequisites

- Ubuntu 18.10
- safe-browser-v0.13.0-linux-x64-dev

**Comment by bochaco** [comment]
Did you include auth req permissions for that container in the auth request @theWebalyst ?

**Comment by bochaco** [comment]
hmmm. I'm sorry, so you get the error even before trying to authorise the app?

**Comment by theWebalyst** [comment]
Thanks Gabriel. This was my code - a missing await causing  getWebIds() to be called prematurely. Closing now.
